# Generated by Django 4.1.3 on 2022-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comissoes',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacoes',
            fields=[
                ('numCotacao', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Numero')),
                ('data', models.DateField()),
                ('nomeFabricante', models.CharField(max_length=200)),
                ('tipoMaterial', models.CharField(max_length=200)),
                ('umMaterial', models.CharField(max_length=10)),
                ('qtdMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motivoReprovacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=200)),
                ('um', models.CharField(max_length=10)),
                ('precoUnit', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('numPedido', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Numero')),
                ('data', models.DateField()),
                ('nomeFabricante', models.CharField(max_length=200)),
                ('tipoMaterial', models.CharField(max_length=200)),
                ('umMaterial', models.CharField(max_length=10)),
                ('qtdMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precoUnitMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precoTotalMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motivoReprovacao', models.CharField(max_length=200)),
                ('numCotacao', models.IntegerField()),
                ('nomCliente', models.CharField(max_length=200)),
                ('percComissao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorComissao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataA30', models.DateField()),
                ('valorB', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataB60', models.DateField()),
                ('valorC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataC90', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='pedidos',
            constraint=models.UniqueConstraint(fields=('numPedido',), name='pedidos_unique'),
        ),
        migrations.AddConstraint(
            model_name='materiais',
            constraint=models.UniqueConstraint(fields=('codigo',), name='materiais_unique'),
        ),
        migrations.AddConstraint(
            model_name='fabricantes',
            constraint=models.UniqueConstraint(fields=('codigo',), name='fabricantes_unique'),
        ),
        migrations.AddConstraint(
            model_name='cotacoes',
            constraint=models.UniqueConstraint(fields=('numCotacao',), name='cotacoes_unique'),
        ),
    ]
