# Generated by Django 4.1.3 on 2022-11-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key='true', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacoes',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('numCotacao', models.IntegerField(default=0)),
                ('data', models.DateField()),
                ('umMaterial', models.CharField(max_length=10)),
                ('qtdMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statusCotacao', models.CharField(default='Em análise', max_length=10)),
                ('motivoReprovacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('codigo', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key='true', serialize=False)),
                ('um', models.CharField(max_length=10)),
                ('precoUnit', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('numPedido', models.IntegerField(default=0)),
                ('data', models.DateField()),
                ('umMaterial', models.CharField(max_length=10)),
                ('qtdMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precoUnitMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precoTotalMaterial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statusPedido', models.CharField(default='Em análise', max_length=10)),
                ('motivoReprovacao', models.CharField(max_length=200)),
                ('valorComissao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataA30', models.DateField()),
                ('valorB', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataB60', models.DateField()),
                ('valorC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataC90', models.DateField()),
                ('nomCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='appcotaki.clientes')),
                ('nomeFabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricantes', to='appcotaki.fabricantes')),
                ('numCotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='appcotaki.cotacoes')),
                ('percComissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='appcotaki.comissoes')),
                ('tipoMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='appcotaki.materiais')),
            ],
        ),
        migrations.AddConstraint(
            model_name='materiais',
            constraint=models.UniqueConstraint(fields=('nome',), name='materiais_unique'),
        ),
        migrations.AddConstraint(
            model_name='fabricantes',
            constraint=models.UniqueConstraint(fields=('codigo',), name='fabricantes_unique'),
        ),
        migrations.AddField(
            model_name='cotacoes',
            name='nomeFabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricante', to='appcotaki.fabricantes'),
        ),
        migrations.AddField(
            model_name='cotacoes',
            name='tipoMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipomateriais', to='appcotaki.materiais'),
        ),
        migrations.AddConstraint(
            model_name='comissoes',
            constraint=models.UniqueConstraint(fields=('percentual',), name='comissoes_unique'),
        ),
        migrations.AddConstraint(
            model_name='clientes',
            constraint=models.UniqueConstraint(fields=('nome',), name='clientes_unique'),
        ),
        migrations.AddConstraint(
            model_name='pedidos',
            constraint=models.UniqueConstraint(fields=('codigo',), name='pedidos_unique'),
        ),
        migrations.AddConstraint(
            model_name='cotacoes',
            constraint=models.UniqueConstraint(fields=('codigo',), name='cotacoes_unique'),
        ),
    ]
