# Generated by Django 4.1.3 on 2022-11-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcotaki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacoes',
            name='nomCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotacaoclientes', to='appcotaki.clientes'),
        ),
    ]
