# Generated by Django 4.1.3 on 2022-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcotaki', '0002_cotacoes_nomcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricantes',
            name='codigo',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
